POST http://localhost:8080/create-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDliNWRiM2ZiNWFjMWMxMmFhZTAzYiIsImlhdCI6MTc0ODQ4NTkyOH0.pad2Wm4R-M_vgykIsN8b5T7XuCKPISsOMNq71VtAPcA

{
    "title": "Nigger nigger nigger 100% certified nigger",
    "banner": "any string",
    "des": "short content",
    "content": { "blocks": [1, 2] }
}

